on:
  push:
  pull_request:

jobs:
  build-and-test:
    name: Build and test
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v4

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.1'
          tools: composer:v2

      - name: Install composer dependencies
        uses: ramsey/composer-install@v3

      - name: PHP-CS-Fixer static analysis
        run: vendor/bin/php-cs-fixer fix --using-cache=no --diff --dry-run -v

      - name: PHPUnit Tests
        run: vendor/bin/phpunit